# Generated by Django 4.2.13 on 2024-07-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not published'), (1, 'Published')], default=0),
        ),
    ]
