# Generated by Django 4.2.13 on 2024-08-15 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0002_remove_booking_duration_remove_booking_time_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AddField(
            model_name='booking',
            name='time_slot',
            field=models.TimeField(default='08:00'),
        ),
    ]
