# Generated by Django 4.2.13 on 2024-08-16 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='type',
        ),
    ]
