# Generated by Django 4.2.13 on 2024-08-16 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StartTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
        migrations.AddField(
            model_name='courttype',
            name='type',
            field=models.CharField(choices=[('GR', 'Grass'), ('GV', 'Gravel')], default='GR', max_length=2),
        ),
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.endtimes'),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.starttimes'),
        ),
    ]
